### Please describe the problem.
hasKey check fails when using a Glacier special remote with a non-default region setting.

### What steps will reproduce the problem?
1. Configure a Glacier special remote with a region other than us-east-1
2. Move some files to the remote
3. Somehow let galcier-cli cache expire. In my case this was waiting for more than 60 hours.
4. Try to copy the file to the glacier remote again.

### What version of git-annex are you using? On what operating system?
5.20140227 on Ubuntu 12.04

### Please provide any additional information below.

[[!format sh """
user@server:$ git annex copy my_file.txt --to glacier
copy my_file.txt (checking glacier...) Traceback (most recent call last):
  File "/bin/glacier", line 730, in <module>
    App().main()
  File "/bin/glacier", line 716, in main
    self.args.func()
  File "/bin/glacier", line 620, in archive_checkpresent
    wait=self.args.wait)
  File "/bin/glacier", line 442, in _vault_sync
    vault = self.connection.get_vault(vault_name)  
  File "/usr/local/lib/python2.7/dist-packages/boto/glacier/layer2.py", line 82, in get_vault
    response_data = self.layer1.describe_vault(name)
  File "/usr/local/lib/python2.7/dist-packages/boto/glacier/layer1.py", line 195, in describe_vault
    return self.make_request('GET', uri)
  File "/usr/local/lib/python2.7/dist-packages/boto/glacier/layer1.py", line 118, in make_request
    raise UnexpectedHTTPResponseError(ok_responses, response)
boto.glacier.exceptions.UnexpectedHTTPResponseError: Expected 200, got (404, code=ResourceNotFoundException, message=Vault not found for ARN: arn:aws:glacier:us-east-1:111111111111:vaults/myvault)
(user error (glacier ["archive","checkpresent","myvault","--quiet","SHA256E-s1111111--aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.JPG"] exited 1)) failed
git-annex: copy: 1 failed
"""]]

> [[fixed|done]]; made it use the same glacierParams as everything else.
> --[[Joey]]
