[[!comment format=mdwn
 username="dharrison@27b3fc3aa4a83cdc03f8e82ab4a8d4f6455e603d"
 nickname="dharrison"
 avatar="http://cdn.libravatar.org/avatar/6390dd09e287547d51c7d848cbd24974"
 subject="MacOSX and Debian cannot decrypt eachother's S3 credentials "
 date="2017-02-08T01:26:08Z"
 content="""
I seem to be hitting a problem with the way git annex encrypts the credentials for S3 remotes. I am creating an S3 remote with shared encryption and embedded credentials. If I create the remote on MacOSX, enableremote fails on Debian. If I create the remote on Debian, enableremote fails on MacOSX with a similar error.  I can enable MacOSX created remotes on other MacOSX systems and Debian created remotes on other Debian systems. 
The enableremote creates a .git/annex/creds/uuid file, but the contents are garbled.

Could this be an issue with different versions of GPG on the systems? 

    Debian 7
    git-annex version: 6.20170101+gitg93d69b1-1~ndall+1
    gpg (GnuPG) 1.4.12

    $ git annex enableremote S3
    enableremote S3 gpg: packet(2) with unknown version 13
      gpg error above was caused by an old git-annex bug in credentials storage. Working around it..
    git-annex: bad creds
    CallStack (from HasCallStack):
      error, called at ./Creds.hs:116:22 in main:Creds

    MacOSX
    git-annex version: 6.20170101
    gpg (GnuPG/MacGPG2) 2.0.30
    libgcrypt 1.6.6

    git annex enableremote S34
    enableremote S34 gpg: [don't know]: invalid packet (ctb=6b)
      gpg error above was caused by an old git-annex bug in credentials storage. Working around it..
    git-annex: bad creds
    CallStack (from HasCallStack):
      error, called at ./Creds.hs:116:22 in main:Creds
"""]]
