[[!comment format=mdwn
 username="http://bigasterisk.com/"
 nickname="Drew Perttula"
 subject="don't see errors"
 date="2013-07-16T03:46:25Z"
 content="""
I don't notice anything funny in the log. Here's the same behavior as before, with the daemon.log lines that are generated.

host1 command:

    ~/annex% date > test-2013-07-15c


host1 new daemon.log lines:

    add test-2013-07-15c (checksum...) ok
    add test-2013-07-15c (checksum...) [2013-07-15 20:41:52 PDT] Committer: Committing changes to git
    [2013-07-15 20:41:52 PDT] Pusher: Syncing with host2.local_annex 
    Already up-to-date.
    X11 forwarding request failed on channel 0
    To ssh://drewp@git-annex-host2.local-drewp_annex/~/annex/
       db4b2ef..ddf6aa7  git-annex -> synced/git-annex
       5f7fa61..24b33b5  master -> synced/master
    Already up-to-date.


host2 new daemon.log lines:

    Updating 5f7fa61..24b33b5
    Fast-forward
     test-2013-07-15c |    1 +
     1 file changed, 1 insertion(+)
     create mode 120000 test-2013-07-15c
    [2013-07-15 20:41:53 PDT] Committer: Committing changes to git
    [2013-07-15 20:41:53 PDT] Pusher: Syncing with host1.local_annex 
    To ssh://drewp@git-annex-host1.local-drewp_annex/~/annex/
       db4b2ef..ddf6aa7  git-annex -> synced/git-annex
    Already up-to-date.


host2 result (broken as before):

    ~/annex% ls -l test-2013-07-15c
    lrwxrwxrwx 1 drewp drewp 180 Jul 15 20:41 test-2013-07-15c -> .git/annex/objects/3Z/FF/SHA256E-s29--dad9d84e460983acfcbf6a2aee25701dd447b56be51c88f79a182ad6c1eeba28/SHA256E-s29--dad9d84e460983acfcbf6a2aee25701dd447b56be51c88f79a182ad6c1eeba28

    ~/annex% cat test-2013-07-15c
    cat: test-2013-07-15c: No such file or directory
"""]]
